eligibility_configs = {
    "lyme": {
        "prefix_diag": "gmh_diagnosis02_1#",
        "prefix_meds": "meds01_1#",
        "suffixes": {
            "kidney": "Kidney_1",
            "bmi": "self_bmi_1",
            "preg": "pregbrstfeed_1",
            "covid": "gmh_currcovid_1",
            "astma_bronchitis": "astma_bronchitis_1",
            "astma_bronchitis_time": "astma_bronchitis_5",
            "antipsychotics_stop": "Antipsychotics_stop_1",
            "antipsychotics": "Antipsychotics_name_1",
            "immunosuppressive_stop": "Immunosupresiva_stop_1",
            "antidepressants": "antidepressants_1",
            "antidepressant_tricyclic": "antidepressant_tricyclic_1",
            "other_stop": "Other_stop_1",
            "steroid_stop": "Therapeuticsteriods_stop_1",
            "painkiller_stop": "Opioids_stop_1",
            "antiviral_stop": "Antiviral_stop_1",
            "antibiotics_stop": "Antibiotics_stop_1",
            "blood_thinners_reason": "bloodthinners_reason_2",
        },
    },
    "me_cfs": {
        "prefix_diag": "gmh_diagnosis02#",
        "prefix_meds": "meds01#",
        "suffixes": {
            "kidney": "Kidney",
            "bmi": "self_bmi",
            "preg": "pregbrstfeed",
            "covid": "gmh_currcovid",
            "phq_score": "phq_2_score",
            "calccageaid": "calccageaid",
            "astma_bronchitis": "astma_bronchitis",
            "astma_bronchitis_time": "astma_bronchitis_4",
            "antipsychotics_stop": "Antipsychotics_stop",
            "antipsychotics": "Antipsychotics_name",
            "immunosuppressive_stop": "Immunosupresiva_stop",
            "antidepressants": "antidepressants",
            "antidepressant_tricyclic": "antidepressant_tricyclic",
            "other_stop": "Other_stop",
            "steroid_stop": "Therapeuticsteriods_stop",
            "painkiller_stop": "Opioids_stop",
            "antiviral_stop": "Antiviral_stop",
            "antibiotics_stop": "Antibiotics_stop",
            "blood_thinners_reason": "bloodthinners_reason_1",
        },
    },
    "post_covid": {
        "prefix_diag": "gmh_diagnosis02_2#",
        "prefix_meds": "meds01_2#",
        "suffixes": {
            "kidney": "Kidney_2",
            "preg": "pregbrstfeed_2",
            "covid": "gmh_currcovid_2",
            "calccageaid": "calccageaid_1",
            "astma_bronchitis": "astma_bronchitis_2",
            "astma_bronchitis_time": "astma_bronchitis_3",
            "antipsychotics_stop": "Antipsychotics_stop_3",
            "antipsychotics": "Antipsychotics_name_2",
            "immunosuppressive_stop": "Immunosupresiva_stop_2",
            "antidepressants": "antidepressants_2",
            "antidepressant_tricyclic": "antidepressant_tricyclic_2",
            "other_stop": "Other_stop_2",
            "steroid_stop": "Therapeuticsteriods_stop_2",
            "painkiller_stop": "Opioids_stop_2",
            "antiviral_stop": "Antiviral_stop_2",
            "antibiotics_stop": "Antibiotics_stop_2",
            "blood_thinners_reason": "bloodthinners_reason_3",
        },
    },
}
